### ISSUE TITLE
Server doesn't support UDP or Datagram

### ISSUE THREAD

**Issue by Makuna** [adafruit/Adafruit_CC3000_Library#125]
The server is hardcoded to TCP stream.  To implement a CoAP (IoT protocol) requires a UDP datagram model.

This seems like exposing this out of the server.Begin with defaults to stream and tcp should work.

I am testing this to see if it works and could provide a pull request.

**Comment by tdicola** [comment]
Yeah it's a great point about UDP support.  The server class was inspired by the Arduino Ethernet library and its interface so that folks could more easily port code over from it: http://arduino.cc/en/Reference/Ethernet  The Ethernet server also only works with TCP, but they do have an EthernetUDP class to receive (and send) UDP messages.  

I think it would probably awesome to follow the model from the Ethernet library and add a similar UDP class that receives and sends UDP messages with a similar interface.  I had briefly looked at this but remember thinking it could be challenging to do since the CC3k socket APIs want you to construct a UDP packet and send it in one call instead of breaking things into a start, send, and end call like the EthernetUDP class.  It could likely be done but might require buffering the data to send in memory which would be annoying and take some of the previous RAM on an Uno, etc.

If you're working on support for a UDP protocol you might want to drop down and use the CC3000's socket APIs directly for now.  Can see details on them here: http://software-dl.ti.com/ecs/simplelink/cc3000/public/doxygen_API/v1.14/html/group__socket__api.html  This would let you get things going without worrying about the interface from the Arduino library.

Also if you're using the firmware version 1.13 be careful as it has some known quirks with UDP (see http://e2e.ti.com/support/wireless_connectivity/f/851/t/342177).  Try upgrading to 1.14 or check out this workaround by calling gethostbyname on localhost (no idea why it works, but it fixes the UDP issues on 1.13): https://github.com/adafruit/Adafruit_CC3000_Library/blob/master/Adafruit_CC3000.cpp#L1240

**Comment by vicatcu** [comment]
@Makuna regarding the comments about the RAM requirements, feel free to drop me an email regarding WildFire, which might be neat to add this functionality to if you find the Uno is too memory constrained.

**Comment by Makuna** [comment]
I have a UDP server up and running, and basically, the CC3000 socket software will hang if it receives a packet larger than 95 bytes (reproducible).  95 bytes works great, 96 hangs.  I tracked it down to bad piece of code in a method SpiTriggerRxProcessing that just goes into a tight loop when the buffer was overwritten.  Which will happen if the chip states it has a packet larger than your buffer.  The issue is, you can't control who sends you data even if you only support packets of a specific size.  Hanging is BAD!  It should just throw the data out and bubble up an error.

**Comment by vicatcu** [comment]
@Makuna this seems like it might be worth promoting to a separate issue. These are the lines you're questioning right? https://github.com/adafruit/Adafruit_CC3000_Library/blob/61a2fd209876596d350569b91fd5f1604a34e620/ccspi.cpp#L564-L569

**Comment by Makuna** [comment]
Yes, that is the hang spot.

**Comment by tdicola** [comment]
Yeah this is a known issue with TI's driver code that we use and has gotten a lot of gripes from folks on TI's forums.  There's a really deep investigation into many issues in TI's drivers that were raised here with spark core's investigation (they use the CC3000 too and similar driver code): https://community.spark.io/t/bug-bounty-kill-the-cyan-flash-of-death/1322

It's a good question if we want to keep this behavior going forward.  I think given that TI has somewhat slowed down the pace of CC3000 releases (and in general are pushing folks to their newer chips) we probably won't expect a ton of new driver updates in the future.  I'm not against changing the logic to be friendly and prevent burying itself in a loop, but it's a good question how things should respond if buffers are overflowed.  Perhaps just inserting some basic length checks (like if the input to a socket send command is over the buffer size return an error code) would be a good start.  We'd want to rationalize whatever new errors we return with how TI defines their socket APIs though (from here http://software-dl.ti.com/ecs/simplelink/cc3000/public/doxygen_API/v1.14/html/group__socket__api.html).

So long rambling reply short, yeah I agree the current behavior is not ideal.  Let's open a new issue around this as a reminder and to keep track of ideas about how to improve the driver behavior without making it too difficult to maintain & integrate TI's changes, and making sure more issues or bugs aren't introduced with the changes.
