### ISSUE TITLE
Arduino Due

### ISSUE THREAD

**Issue by elhomiloko** [adafruit/Adafruit_CC3000_Library#144]
Hello,

I have a query. This library works with Arduino Due and the CC3000 Shield? and What Arduino IDE version should be used? Sorry for my ignorance and my English.

Thank you!

**Comment by tdicola** [comment]
Yep the Due should work, but one thing to note with the shield and the Due is that you'll need to solder closed a few jumpers so that the shield uses a SPI connection through the ICSP header.  Check out the bottom of the page here: https://learn.adafruit.com/adafruit-cc3000-wifi/cc3000-shield  

For the Arduino version try Arduino 1.6.4, but if you run into stability issues you might want to jump back to the last version before the change to the newer compiler (so version 1.5.6-r2 beta from the older downloads page: https://www.arduino.cc/en/Main/OldSoftwareReleases).
