### ISSUE TITLE
Allow begin and stop functions to be called multiple times

### ISSUE THREAD

**Issue by tdicola** [adafruit/Adafruit_CC3000_Library#78]
There are a few issues with begin() and stop() using the _intialized variable which mean these functions really can't be called multiple times.  Begin will check if initialized and skip all further logic, however this is problematic because it will skip things like calling wlan_start() to turn the CC3000 on if it was off.  The firmware update sketch ran into this issue and a workaround was to just call wlan_start() manually.  Related to this, stop() doesn't set intialized to false so again begin() won't turn the CC3000 back on (user [here](http://forums.adafruit.com/viewtopic.php?f=22&t=54564&p=275977#p275977) ran into the problem).

Opening this as a bug for now to come back to and investigate what _initialized is protecting from running multiple times and how to allow a scenario of begin(), stop(), begin() to work as expected by turning on, off, and then on again the CC3000.

**Comment by dzzie** [comment]
+1 I just ran into this behavior myself. I had to stop the CC3000 every time after use in order to use the capacitive touch screen library and ran into problems calling .begin multiple times. (It worked the second time, but then would hang in checkDHCP on the third)

I found two stable scenarios,

1) 
* global Adafruit_CC3000
* call .begin in setup()
* in postdata function, initilize with .reboot, .deleteProfiles then at end of function call .disconnect, .stop

This could be repeated multiple times without hang

2) use a local Adafruit_CC3000 object variable inside the one function which did the data post. Then you could call .begin everytime fresh and it did not lead to hangs.

(*the FT6206.touched() function would cause a lockup when used with the CC3000 breakout if I didnt call CC3000.stop after use)
